# Generated by Django 5.2.7 on 2025-10-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cfop",
            fields=[
                (
                    "cfop_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cfop_codigo",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Código"
                    ),
                ),
                (
                    "cfop_operacao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Operação"
                    ),
                ),
                (
                    "cfop_integracao",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Integração"
                    ),
                ),
                (
                    "cfop_tipo",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Entrada"), (2, "Saída")],
                        null=True,
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "CFOP",
                "verbose_name_plural": "CFOPs",
                "db_table": "cfop",
                "ordering": ["cfop_codigo"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "cliente_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cliente_nome",
                    models.CharField(max_length=45, verbose_name="Cliente"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "cliente",
            },
        ),
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "convenio_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "convenio_nome",
                    models.CharField(max_length=45, verbose_name="Convênio"),
                ),
                ("convenio_preco", models.FloatField(verbose_name="Preço")),
            ],
            options={
                "verbose_name": "Convênio",
                "verbose_name_plural": "Convênios",
                "db_table": "convenio",
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "empresa_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "empresa_nome",
                    models.CharField(max_length=45, verbose_name="Empresa"),
                ),
            ],
            options={
                "verbose_name": "Emmpresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresa",
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "fornecedor_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fornecedor_nome",
                    models.CharField(max_length=100, verbose_name="Fornecedor"),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "db_table": "fornecedor",
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "funcionario_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "funcionario_nome",
                    models.CharField(max_length=100, verbose_name="Funcionário"),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "db_table": "funcionario",
            },
        ),
        migrations.CreateModel(
            name="GrupoMercadoria",
            fields=[
                (
                    "grupo_mercadoria_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "grupo_mercadoria_nome",
                    models.CharField(max_length=45, verbose_name="Grupo"),
                ),
            ],
            options={
                "verbose_name": "Grupo de Mercadoria",
                "verbose_name_plural": "Grupos de Mercadorias",
                "db_table": "grupo_mercadoria",
            },
        ),
        migrations.CreateModel(
            name="PlanoConta",
            fields=[
                (
                    "plano_conta_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "plano_conta_nome",
                    models.CharField(max_length=50, verbose_name="Conta"),
                ),
            ],
            options={
                "verbose_name": "Plano de Conta",
                "verbose_name_plural": "Planos de Conta",
                "db_table": "plano_conta",
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "veiculo_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "veiculo_placa",
                    models.CharField(max_length=45, verbose_name="Placa"),
                ),
                (
                    "veiculo_modelo",
                    models.CharField(max_length=45, verbose_name="Modelo"),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "db_table": "veiculo",
            },
        ),
        migrations.CreateModel(
            name="ConvenioGrupoMercadoria",
            fields=[
                (
                    "convenio_grupo_mercadoria_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        db_column="convenio_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.convenio",
                    ),
                ),
                (
                    "grupo_mercadoria",
                    models.ForeignKey(
                        db_column="grupo_mercadoria_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.grupomercadoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convênio por Grupo de Mercadoria",
                "verbose_name_plural": "Convênios por Grupo de Mercadoria",
                "db_table": "convenio_grupo_mercadoria",
            },
        ),
        migrations.CreateModel(
            name="ClienteConvenioGrupoMercadoria",
            fields=[
                (
                    "cliente_convenio_grupo_mercadoria_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cliente",
                    ),
                ),
                (
                    "convenio_grupo_mercadoria",
                    models.ForeignKey(
                        db_column="convenio_grupo_mercadoria_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.conveniogrupomercadoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convênio do Cliente",
                "verbose_name_plural": "Convênios dos Clientes",
                "db_table": "cliente_convenio_grupo_mercadoria",
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "compra_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "compra_numero",
                    models.CharField(max_length=10, verbose_name="Número da Compra"),
                ),
                (
                    "compra_data_entrada",
                    models.DateField(verbose_name="Data de Entrada"),
                ),
                (
                    "compra_data_saida_fornecedor",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Saída do Fornecedor",
                    ),
                ),
                (
                    "compra_prazo_pagamento",
                    models.CharField(verbose_name="Prazo de Pagamento"),
                ),
                (
                    "compra_data_base",
                    models.DateField(blank=True, null=True, verbose_name="Data Base"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="fornecedor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.fornecedor",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        blank=True,
                        db_column="plano_conta_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.planoconta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "db_table": "compra",
            },
        ),
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                ("conta_pagar_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "conta_pagar_historico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "conta_pagar_numero_documento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("conta_pagar_data_emissao", models.DateField(blank=True, null=True)),
                (
                    "conta_pagar_data_vencimento",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "conta_pagar_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "conta_pagar_portador",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "conta_pagar_nosso_numero",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        db_column="compra_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.compra",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="fornecedor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.fornecedor",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        db_column="plano_conta_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.planoconta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a Pagar",
                "verbose_name_plural": "Contas a Pagar",
                "db_table": "conta_pagar",
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "pagamento_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pagamento_data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "pagamento_valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "pagamento_forma_pagamento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "pagamento_observacao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "conta_pagar",
                    models.ForeignKey(
                        db_column="conta_pagar_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contapagar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "db_table": "pagamento",
            },
        ),
        migrations.CreateModel(
            name="ContasReceber",
            fields=[
                (
                    "contas_receber_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "contas_receber_historico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contas_receber_numero_documento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contas_receber_data_emissao",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "contas_receber_data_vencimento",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "contas_receber_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "contas_receber_portador",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contas_receber_nosso_numero",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        db_column="plano_conta_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.planoconta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a Receber",
                "verbose_name_plural": "Contas a Receber",
                "db_table": "contas_receber",
            },
        ),
        migrations.CreateModel(
            name="Caixa",
            fields=[
                ("caixa_id", models.AutoField(primary_key=True, serialize=False)),
                ("caixa_data_emissao", models.DateField(blank=True, null=True)),
                (
                    "caixa_historico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "caixa_valor_entrada",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "caixa_valor_saida",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="empresa_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        db_column="plano_conta_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.planoconta",
                    ),
                ),
            ],
            options={
                "verbose_name": "caixa",
                "verbose_name_plural": "Caixa",
                "db_table": "caixa",
                "ordering": ["-caixa_data_emissao"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("produto_id", models.AutoField(primary_key=True, serialize=False)),
                ("produto_nome", models.CharField(max_length=100)),
                ("produto_unidade_medida", models.CharField(max_length=20)),
                ("produto_preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="fornecedor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.fornecedor",
                    ),
                ),
                (
                    "grupo_mercadoria",
                    models.ForeignKey(
                        db_column="grupo_mercadoria_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.grupomercadoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "produto",
            },
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "compra_item_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "compra_item_qtd",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Qtde"
                    ),
                ),
                (
                    "compra_item_preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                ("compra_item_volume", models.IntegerField(verbose_name="Volume")),
                (
                    "cfop",
                    models.ForeignKey(
                        db_column="cfop_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cfop",
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        db_column="compra_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.compra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="produto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra Item",
                "verbose_name_plural": "Compra Itens",
                "db_table": "compra_item",
            },
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                ("recebimento_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "recebimento_data_recebimento",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "recebimento_valor_recebido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "recebimento_forma_recebimento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recebimento_observacao",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contas_receber",
                    models.ForeignKey(
                        db_column="contas_receber_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contasreceber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebimento",
                "verbose_name_plural": "Recebimentos",
                "db_table": "recebimento",
            },
        ),
        migrations.CreateModel(
            name="Romaneio",
            fields=[
                (
                    "romaneio_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "romaneio_data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "produto_item_qtd",
                    models.FloatField(blank=True, null=True, verbose_name="Quantidade"),
                ),
                (
                    "produto_item_volume",
                    models.FloatField(blank=True, null=True, verbose_name="Volume"),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        blank=True,
                        db_column="compra_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.compra",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        db_column="funcionario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.funcionario",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        db_column="veiculo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Romaneio",
                "verbose_name_plural": "Romaneios",
                "db_table": "romaneio",
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                ("venda_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "venda_data_emissao",
                    models.DateField(verbose_name="Data de Emissão"),
                ),
                (
                    "venda_data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "romaneio",
                    models.ForeignKey(
                        blank=True,
                        db_column="romaneio_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.romaneio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "db_table": "venda",
            },
        ),
        migrations.AddField(
            model_name="contasreceber",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                db_column="venda_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.venda",
            ),
        ),
        migrations.CreateModel(
            name="VendaItem",
            fields=[
                ("vend_item_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "venda_item_qtd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "venda_item_preco",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço",
                    ),
                ),
                (
                    "venda_item_volume",
                    models.IntegerField(blank=True, null=True, verbose_name="Volume"),
                ),
                (
                    "cfop",
                    models.ForeignKey(
                        db_column="cfop_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cfop",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cliente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="produto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        db_column="venda_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda Item",
                "verbose_name_plural": "Venda Itens",
                "db_table": "venda_item",
            },
        ),
    ]
