# Generated by Django 5.2.7 on 2025-10-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendaitem",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                db_column="venda_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.venda",
            ),
        ),
    ]
