# Generated by Django 5.2.6 on 2025-10-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_vendaitem_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendaitem",
            name="plano_conta",
            field=models.ForeignKey(
                blank=True,
                db_column="plano_conta_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.planoconta",
            ),
        ),
    ]
