# Generated by Django 5.2.6 on 2025-10-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_plano_conta_to_vendaitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfop",
            name="cfop_integracao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("receber", "Contas a Receber"),
                    ("pagar", "Contas a Pagar"),
                    ("caixa", "Livro Caixa"),
                    ("estoque", "Não Movimenta Estoque"),
                    ("caixa/cheque", "Caixa/Cheque Pré-datado"),
                    ("estoque/caixa", "Não Movimenta Estoque + Livro Caixa"),
                    ("estoque/pagar", "Não Movimenta Estoque + Contas a Pagar"),
                    ("estoque/receber", "Não Movimenta Estoque + Contas a Receber"),
                ],
                max_length=50,
                null=True,
                verbose_name="Integração",
            ),
        ),
    ]
