# Generated by Django 5.2.6 on 2025-10-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_cfop_cfop_integracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="plano_conta",
            field=models.ForeignKey(
                blank=True,
                db_column="plano_conta_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.planoconta",
                verbose_name="Plano de Contas",
            ),
        ),
    ]
