# Generated by Django 5.2.6 on 2025-10-03 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_venda_plano_conta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planoconta",
            options={
                "ordering": ["plano_conta_numero", "plano_conta_nome"],
                "verbose_name": "Plano de Conta",
                "verbose_name_plural": "Planos de Conta",
            },
        ),
        migrations.AddField(
            model_name="planoconta",
            name="plano_conta_numero",
            field=models.CharField(
                blank=True,
                help_text="1=Receita, 3=Despesa, 5=Banco",
                max_length=20,
                null=True,
                verbose_name="Número da Conta",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="plano_conta",
            field=models.ForeignKey(
                db_column="plano_conta_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.planoconta",
                verbose_name="Plano de Contas",
            ),
            preserve_default=False,
        ),
    ]
