# Generated by Django 5.2.6 on 2025-10-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_planoconta_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendaitem",
            name="plano_conta",
            field=models.ForeignKey(
                db_column="plano_conta_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.planoconta",
            ),
            preserve_default=False,
        ),
    ]
