# Generated by Django 5.2.6 on 2025-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_vendaitem_plano_conta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendaitem",
            name="venda_item_preco",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Preço"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vendaitem",
            name="venda_item_qtd",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Quantidade"
            ),
            preserve_default=False,
        ),
    ]
