# Generated by Django 5.2.6 on 2025-10-05 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_vendaitem_venda_item_preco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="produto_preco_custo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço de custo usado quando a venda não tem romaneio",
                max_digits=10,
                null=True,
                verbose_name="Preço de Custo",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="plano_conta",
            field=models.ForeignKey(
                db_column="plano_conta_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.planoconta",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produto",
            name="produto_preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço de Venda"
            ),
        ),
    ]
