# Generated by Django 5.2.6 on 2025-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_produto_produto_preco_custo_alter_compra_plano_conta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="romaneio",
            name="status",
            field=models.CharField(
                choices=[("aberto", "Aberto"), ("fechado", "Fechado")],
                default="aberto",
                help_text="Status definido manualmente: Aberto ou Fechado",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
