# Generated by Django 4.2.25 on 2025-10-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_romaneio_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="compra_prazo_pagamento",
            field=models.CharField(max_length=50, verbose_name="Prazo de Pagamento"),
        ),
        migrations.AlterField(
            model_name="romaneio",
            name="status",
            field=models.CharField(
                choices=[("aberto", "ABERTO"), ("fechado", "FECHADO")],
                default="aberto",
                help_text="Status definido manualmente: Aberto ou Fechado",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
