# Generated by Django 4.2.25 on 2025-10-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_romaneio_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendaitem",
            name="venda_item_preco_custo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço de custo do produto no momento da venda",
                max_digits=10,
                null=True,
                verbose_name="Preço de Custo",
            ),
        ),
    ]
