# Generated by Django 4.2.25 on 2025-10-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_venda_item_preco_custo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendaitem",
            name="venda_item_preco_custo",
        ),
    ]
