"""
Django settings for compufour project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#psoivph#vlnq)$$nd$bfg%wjz6$vu^3cun&ma92v2tq%_+*5e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['ricartejr.pythonanywhere.com', '127.0.0.1']
ALLOWED_HOSTS = ['72.60.253.150', 'r3sys.com.br', 'www.r3sys.com.br', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    #'grappelli',
    #'jazzmin',
    "admin_interface",
    "colorfield",
    "rangefilter",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'core.apps.CoreConfig',
]
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "compufour.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "compufour.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# Formato de exibição de data
DATE_FORMAT = 'd/m/Y'  # Define o formato dd/mm/yyyy

# Formato de entrada de data (para campos de input no admin)
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',  # dd/mm/yyyy
    '%d/%m/%y',   # dd/mm/yy
    '%Y-%m-%d',   # yyyy-mm-dd (formato padrão do Django, mantido para compatibilidade)
]

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

JAZZMIN_SETTINGS = {
    "site_title": "Compufour",
    "site_header": "Compufour",
    "site_brand": "Compufour",
    "welcome_sign": "Compufour",
    "copyright": "Compufour © 2025",

    # Layout com Bootstrap
    "theme": "pulse",  # temas bootstrap (cyborg, litera, lumen, etc.)
    #"dark_mode_theme": "darkly",  # se quiser tema escuro automático

    # Logo
    "site_logo": "img/logo.png",   # coloque seu logo em static/img/logo.png
    "site_logo_classes": "img-circle", 

    # Customização de cores (via bootstrap variables)
    "button_classes": {
        #"primary": "btn btn-success",
        #"secondary": "btn btn-secondary",
        #"info": "btn btn-info",
        #"warning": "btn btn-warning",
        #"danger": "btn btn-danger",
    },

    # Ícones (FontAwesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "core": "fas fa-industry",
        "core.Empresa": "fas fa-building",
        "core.Fornecedor": "fas fa-truck",
        "core.Cliente": "fas fa-user-tie",
        "core.Convenio": "fas fa-handshake",
        "core.GrupoMercadoria": "fas fa-layer-group",
        "core.Produto": "fas fa-boxes",
        "core.Cfop": "fas fa-receipt",
        "core.Funcionario": "fas fa-user-cog",
        "core.Veiculo": "fas fa-truck-moving",
        "core.PlanoConta": "fas fa-file-invoice",
        "core.Compra": "fas fa-shopping-cart",
        "core.CompraItem": "fas fa-list-ol",
        "core.ContaPagar": "fas fa-file-invoice-dollar",
        "core.ContasReceber": "fas fa-hand-holding-usd",
        "core.Pagamento": "fas fa-money-check-alt",
        "core.Recebimento": "fas fa-money-bill-wave",
        "core.Caixa": "fas fa-cash-register",
        "core.Romaneio": "fas fa-clipboard-list",
        "core.Venda": "fas fa-shopping-bag",
        "core.VendaItem": "fas fa-tags",
        "core.ConvenioGrupoMercadoria": "fas fa-object-group",
        "core.ClienteConvenioGrupoMercadoria": "fas fa-users",
    },

    # Ordem dos apps e models no menu
    "order_with_respect_to": [
        "auth",
        "core",
        "core.Empresa",
        "core.Cliente",
        "core.Fornecedor",
        "core.Produto",
        "core.Caixa",
        "core.ContasReceber",
        "core.Recebimento",
        "core.ContaPagar",
        "core.Pagamento",
        "core.Compra",
        "core.CompraItem",
        "core.Venda",
        "core.VendaItem",
        "core.PlanoConta",
        "core.Convenio",
        "core.ConvenioGrupoMercadoria",
        "core.ClienteConvenioGrupoMercadoria",
        "core.Funcionario",
        "core.GrupoMercadoria",
        "core.Cfop",
        "core.Veiculo",
        "core.Romaneio",
    ],

    # Custom menu
    "custom_links": {
        "core": [
            {
                "name": "Relatórios",
                "url": "/admin/core/relatorios/",
                "icon": "fas fa-chart-line",
                "permissions": ["core.view_relatorio"],
            },
        ]
    },

    # Links externos
    "topmenu_links": [
        {"name": "Início", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Documentação", "url": "https://docs.djangoproject.com", "new_window": True},
    ],
    "custom_css": "css/custom_jazzmin.css",  # Caminho para o CSS
}
JAZZMIN_UI_TWEAKS = {
    "theme": "pulse",
}

ADMIN_MENU_APP_ORDER = [item for item in JAZZMIN_SETTINGS['order_with_respect_to'] if '.' not in item]
ADMIN_MENU_MODEL_ORDER = [item for item in JAZZMIN_SETTINGS['order_with_respect_to'] if '.' in item]
